all : lab11_serv lab11_client lab11
lab11_serv : lab11_serv.c
		gcc -o lab11_serv lab11_serv.c
lab11_client : lab11_client.c
		gcc -o lab11_client lab11_client.c
lab11 : lab11.c
		gcc -o lab11 lab11.c
clean :
		rm lab11_serv lab11_client lab11
